version: 2
env:
  - CGO_ENABLED=0
  - APP_NAME=psi-map

builds:
  - id: cli
    main: ./cmd/cli/main.go
    binary: "{{ .Env.APP_NAME }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
  
  - id: api
    main: ./cmd/api/main.go
    binary: "{{ .Env.APP_NAME }}-api"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .Env.APP_NAME }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        formats: ["zip"]
    formats: ["tar.gz"]

checksum:
  name_template: "{{ .Env.APP_NAME }}_{{ .Version }}_checksums.txt"

changelog:
  use: github
  sort: asc
  abbrev: 7
  format: "`{{ .SHA }}`](https://github.com/mattjh1/{{ .Env.APP_NAME }}/commit/{{ .SHA }}): {{ .Message }} ({{ .AuthorUsername }})"
  filters:
    exclude:
      - "^docs(\\(.*\\))?:"
      - "^chore(\\(.*\\))?:"
      - "^ci(\\(.*\\))?:"
      - "^test(\\(.*\\))?:"
      - "^refactor(\\(.*\\))?:"

release:
  github:
    owner: mattjh1
    name: psi-map
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto

before:
  hooks:
    - make ci-test
