name: Security Scan
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
permissions:
  contents: read
  security-events: write
  actions: read

env:
  SKIP_PATTERNS: '^(docs:|chore:|refactor:|test:).*'

jobs:
  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message
        id: skipcheck
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ $SKIP_PATTERNS ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit early if skipping
        if: steps.skipcheck.outputs.skip != 'true'
        run: echo "Skipping Gosec due to commit prefix"
            
      - name: Checkout code
        if: steps.skipcheck.outputs.skip != 'true'
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        if: steps.skipcheck.outputs.skip != 'true'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: always() && steps.skipcheck.outputs.skip != 'true'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy

  gosec_scan:
    name: Go Security Scan
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' # don't run during screduled runs
    
    steps:
      - name: Skip commit prefixes (docs/chore/ci/refactor/test)
        id: skipcheck
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ $SKIP_PATTERNS ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit early if skipping
        if: steps.skipcheck.outputs.skip == 'true'
        run: echo "Skipping Gosec due to commit prefix"
        
      - name: Checkout code
        if: steps.skipcheck.outputs.skip != 'true'
        uses: actions/checkout@v4
        
      - name: Set up Go
        if: steps.skipcheck.outputs.skip != 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Run Gosec Security Scanner
        if: steps.skipcheck.outputs.skip != 'true'
        uses: securego/gosec@v2.21.4
        with:
          args: '-no-fail -fmt sarif -out gosec-results.sarif ./...'
          
      - name: Upload SARIF to GitHub
        if: steps.skipcheck.outputs.skip != 'true'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: gosec-results.sarif
          category: gosec
          wait-for-processing: true
